### ISSUE TITLE
Float exponent JSON -> EXI

### ISSUE THREAD

**Issue by heyjulian** [EXIficient/exificient-for-json.c#5]
Parsing of floating point values with exponent is not handled but is valid JSON as shown at http://www.json.org/ .

e.g. 1e500 will be parsed as 1500

Location: EXIforJSONEncoder.c::dumpFloat

**Comment by danielpeintner** [comment]
Commit https://github.com/EXIficient/exificient-for-json.c/commit/f8d56257e70c37efb5ce094165b837000bf0ef98 should resolve the issue. Correct?

**Comment by heyjulian** [comment]
Correct.
